Done Task2
itechart-mogilev-lab/bondareva pull request #2
Opened 2019-01-28 20:56 UTC by VikaBondareva

https://vikabondareva.github.io

2019-01-29 16:47 UTC, AnastasiyaTalstyka requested changes
Визуально придраться практически не к чему. 
Разве что на мобильной версии из-за выпирающей ленты скрол влево-вправо появляется, header и footer не навесь экран растянуты (справа белый край)
Иконку добавить

Вопросы касательно БЭМа:

.header__nav_top-left {
	 position: absolute;
	 right: 60px;
}
.search-form_ritght 
.main_center и др.
Модификаторами не позиционируется. Позиционируется через родительский блок https://ru.bem.info/methodology/css/#%D0%92%D0%BD%D0%B5%D1%88%D0%BD%D1%8F%D1%8F-%D0%B3%D0%B5%D0%BE%D0%BC%D0%B5%D1%82%D1%80%D0%B8%D1%8F-%D0%B8-%D0%BF%D0%BE%D0%B7%D0%B8%D1%86%D0%B8%D0%BE%D0%BD%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5 Вот классу .header__nav ты можешь передать эти свойства. Или добавить класс page__main. 

Блоки не могут иметь свойство position  и margin
Header position relative
menu_small — марджин
user-inform — марджин
Footer — марджин и др.
￼
Здесь визуально один блок, было бы лучше объединить

На будущее: есть такое понятие как css Reset в минимальном виде выглядит так *{margin: 0, padding: 0}. Спасет от дефолтных стилей тегов и постоянных margin:0 в документе 

class="headline header__title"  элемент должен содержать имя блока, header__headline

headline__h1 может придирка, но название не очень, лучше headline__main-header  и headline__subheader

burger__check — элемент всегда часть блока класс .burger надо сделать оберткой для label и input

text-uppercase — не по БЭМ, явно не блок, надо сделать элементом блока.

2019-01-30 17:25 UTC, anastasiatol commented on task2 (BEM, Adaptation)/index.html
> +					<button class="article__button button_orange text_uppercase">More</button>
По БЭМ не хватает название блока или элумента без модификатора

2019-01-30 17:32 UTC, anastasiatol commented on task2 (BEM, Adaptation)/style/common.block/common.css
> +.text_uppercase{
для БЭМ такое не оч хорошо. При том ты используешь uppercase и raleway в одних и тех же классах. На мой взгляд лучше это свой ство например в button дописать

2019-01-30 17:34 UTC, anastasiatol requested changes
Если сначала открыть в неполном окне, открыть/закрть сайдбар, а потом развернуть на полный экран, отображается вот так:
![screen shot 2019-01-30 at 20 32 34](https://user-images.githubusercontent.com/30156652/52000508-58038780-24ce-11e9-8d06-3e11fde569d0.png)

2019-02-01 06:28 UTC, anastasiatol commented on task2 (BEM, Adaptation)/index.html
> +						<div class="item-li list-section__item-li""><a class="href" href="#">Communications</a></div>
Кавычки лишние во всех элементах

2019-02-01 06:32 UTC, anastasiatol commented on task2 (BEM, Adaptation)/index.html
> +				<li class="item menu__item"><a class="href href_white" href="#"><i class="fas fa-home icom menu__icon"></i>Home</a></li>
Я бы не выделяла так много блоков. Меню визуально целый компонент

2019-02-01 06:33 UTC, anastasiatol commented on task2 (BEM, Adaptation)/style/common.block/menu.css
> +.href{
это тоже можно было через css reset сделать в начале документа 
a {...}

2019-02-01 06:36 UTC, merged